# Generated by Django 4.2.6 on 2023-11-16 04:07

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("activities", "0003_alter_activity_owner"),
    ]

    operations = [
        migrations.CreateModel(
            name="ActivityEvent",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated at")),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now, verbose_name="Created at")),
                ("scheduled_on", models.DateField(verbose_name="Scheduled on")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("IN_PROGRESS", "In progres"),
                            ("REJECTED", "Rejected"),
                            ("COMPLETED", "Completed"),
                        ],
                        default="PENDING",
                        max_length=11,
                        verbose_name="Status",
                    ),
                ),
                (
                    "completion_time",
                    models.DateTimeField(
                        blank=True,
                        help_text="Describes whether and when activity has been completed for scheduled date",
                        null=True,
                        verbose_name="Completion time",
                    ),
                ),
                (
                    "ongoing_activity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="completions",
                        to="activities.ongoingactivity",
                        verbose_name="Ongoing activity",
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="ActivityCompletion",
        ),
        migrations.AddIndex(
            model_name="activityevent",
            index=models.Index(fields=["scheduled_on"], name="activities__schedul_d1c998_idx"),
        ),
        migrations.AddIndex(
            model_name="activityevent",
            index=models.Index(fields=["status"], name="activities__status_fb7647_idx"),
        ),
    ]
