# Generated by Django 4.2.6 on 2023-11-16 19:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("activities", "0005_alter_activityevent_ongoing_activity"),
    ]

    operations = [
        migrations.AlterField(
            model_name="activityevent",
            name="scheduled_on",
            field=models.DateTimeField(verbose_name="Scheduled on"),
        ),
    ]
