# Generated by Django 4.2.6 on 2023-11-16 04:07

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("activities", "0004_activityevent_delete_activitycompletion_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CalendarEntry",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated at")),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now, verbose_name="Created at")),
                ("integration_type", models.CharField(max_length=15, verbose_name="Integration type")),
                (
                    "external_identifier",
                    models.CharField(
                        help_text="Unique identifier of the calendar entry in the external system.",
                        max_length=256,
                        unique=True,
                        verbose_name="External identifier",
                    ),
                ),
                (
                    "activity_completion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="calendar_entries",
                        to="activities.activityevent",
                        verbose_name="Activity completion",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
