# Generated by Django 4.2.6 on 2023-11-16 08:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("integrations", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="calendarentry",
            old_name="activity_completion",
            new_name="activity_event",
        ),
    ]
